name: device_auto_rotate_checker
description: A flutter plugin to check if device auto rotate is on or off.
version: 0.0.1+1
repository: https://github.com/mpcreza/device_auto_rotate_checker

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.device_auto_rotate_checker
        pluginClass: DeviceAutoRotateCheckerPlugin
